spring:
  application:
    name: demo
  web:
    resources:
      static-locations: classpath:/static/, classpath:/static/bootstrap/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/db01?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
  security:
    user:
      name: user
      password: 1234
  messages:
    encoding: UTF-8
    basename: messages_ko_KR
  kafka:
    bootstrap-servers: kafka:9092
logging:
  level:
    root: info
    com.example.demo: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.zaxxer.hikari: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
jwt:
  secret: "0123456789abcdef0123456789abcdef"