apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base/namespace.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/configmap.yaml
  - ../../base/secret.yaml
  - ../../base/mysql-deployment.yaml
  - ../../mysql-service.yaml

patchesStrategicMerge:
  - configmap-patch.yaml
